data:
    path_aerial_train: "/home/pascal/FLAIR-2/data/flair_aerial_train/" # ./flair_aerial_train/
    path_sen_train: "/home/pascal/FLAIR-2/data/flair_sen_train/"  # ./flair_sen_train/
    path_labels_train: "/home/pascal/FLAIR-2/data/flair_labels_train/" # ./flair_labels_train/
 
    path_aerial_test: "/home/pascal/FLAIR-2/data/flair_2_aerial_test/" # ./flair_2_aerial_test/
    path_sen_test: "/home/pascal/FLAIR-2/data/flair_2_sen_test/" # ./flair_2_sen_test/
    path_labels_test: "/home/pascal/FLAIR-2/data/flair_2_labels_test/" # ./flair_2_labels_test/

    path_sp_centroids: "/home/pascal/FLAIR-2/data/flair_2_centroids_sp_to_patch/flair-2_centroids_sp_to_patch.json" # ./flair_2_centroids_sp_to_patch.json
    path_metadata_aerial: "/home/pascal/FLAIR-2/data/flair_2_aerial_metadata/flair_aerial_metadata.json" # ./flair_aerial_metadata.json

HF_data_path : "/home/pascal/FLAIR-2/data/unzip" # Path to unzipped FLAIR HF dataset
domains_train : ["D006_2020","D007_2020","D008_2019","D009_2019","D013_2020","D016_2020","D017_2018","D021_2020","D023_2020","D030_2021","D032_2019","D033_2021","D034_2021","D035_2020","D038_2021","D041_2021","D044_2020","D046_2019","D049_2020","D051_2019","D052_2019","D055_2018","D060_2021","D063_2019","D070_2020","D072_2019","D074_2020","D078_2021","D080_2021","D081_2020","D086_2020","D091_2021"]
domains_val : ["D004_2021","D014_2020","D029_2021","D031_2019","D058_2020","D066_2021","D067_2021","D077_2021"]   
domains_test : ["D015_2020","D022_2021","D026_2020","D036_2020","D061_2020","D064_2021","D068_2021","D069_2020","D071_2020","D084_2021"]

out_folder: "/home/pascal/FLAIR-2/data/flair2/"
out_model_name: "flair-2-baseline"



#Fusion
sat_patch_size: 40 # in [8,112] and multiple of 8 
w_unet_utae: [1,1]
drop_utae_modality: 0.0 # 1 = dropping U-TAE branch

# MTD and AUG
aerial_metadata: True
geo_enc_size: 32
use_augmentation: True

# Sentinel Time Series filtering
filter_clouds: True
average_month: True

# Weighting
weights_aerial_satellite:
                         building               : [1,1]
                         pervious surface       : [1,1]
                         impervious surface     : [1,1]
                         bare soil              : [1,1]
                         water                  : [1,1]
                         coniferous             : [1,1]
                         deciduous              : [1,1]
                         brushwood              : [1,1]
                         vineyard               : [1,1]
                         herbaceous vegetation  : [1,1]
                         agricutural land       : [1,1]
                         plowed land            : [1,0]
                         other                  : [0,0]

# Inputs
num_classes: 13
num_channels_aerial: 5 
num_channels_sat: 10 
# Training
num_epochs: 100
batch_size: 10
batch_size_inference: 1
lr: 0.001

# Computation
num_workers: 10
accelerator: cpu # gpu or cpu
gpus_per_node: 1
num_nodes: 1
strategy: null # ddp if multi-gpu


# UTAE Model
encoder_widths: [64,64,128,128] # 1st and last must be equivalent to decoder_widths
decoder_widths: [64,64,128,128] # 1st and last must be equivalent to encoder_widths
out_conv: [32, 13]
str_conv_k: 4
str_conv_s: 2
str_conv_p: 1
agg_mode: att_group
encoder_norm: group
n_head: 16
d_model: 256
d_k: 4
ref_year: 2021 # defined for whole dataset
ref_date: 05-15 # defined for whole dataset
pad_value: 0
padding_mode: reflect

#Tracking
enable_progress_bar: True
progress_rate: 10
